basePath: /
definitions:
  transformers.APITransformer:
    properties:
      name:
        type: string
      purpose:
        type: string
      version:
        type: string
    type: object
  transformers.SampleTransformer:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  transformers.ValidationErrorTransformer:
    properties:
      trace: {}
      type:
        type: string
    type: object
  unpackers.SampleUnpacker:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
host: localhost:3000
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: StoryBuilder REST API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: StoryBuilder API
  version: 0.0.1
paths:
  /:
    get:
      description: Returns metadata about the running API (name, version, purpose)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transformers.APITransformer'
      summary: Get API information
      tags:
      - information
  /samples:
    get:
      description: Returns a collection of samples
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/transformers.SampleTransformer'
            type: array
      summary: Get samples list
      tags:
      - samples
    post:
      consumes:
      - application/json
      description: Creates a sample resource
      parameters:
      - description: Sample payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/unpackers.SampleUnpacker'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/transformers.SampleTransformer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transformers.ValidationErrorTransformer'
      summary: Create a new sample
      tags:
      - samples
  /samples/{id}:
    delete:
      description: Deletes a sample resource
      parameters:
      - description: Sample ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transformers.ValidationErrorTransformer'
      summary: Delete a sample
      tags:
      - samples
    get:
      description: Returns a single sample resource
      parameters:
      - description: Sample ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transformers.SampleTransformer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transformers.ValidationErrorTransformer'
      summary: Get sample by ID
      tags:
      - samples
    put:
      consumes:
      - application/json
      description: Updates a sample resource
      parameters:
      - description: Sample ID
        in: path
        name: id
        required: true
        type: integer
      - description: Sample payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/unpackers.SampleUnpacker'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transformers.ValidationErrorTransformer'
      summary: Update a sample
      tags:
      - samples
schemes:
- http
swagger: "2.0"
